"""baseline: initial 12 tables

Revision ID: 40ffbb1d3136
Revises: 
Create Date: 2026-08-31 13:14:42.601656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ffbb1d3136'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_dept',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('leader', sa.String(length=64), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_dict_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_dict_item_type_code'), 'sys_dict_item', ['type_code'], unique=False)
    op.create_table('sys_dict_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_dict_type_code'), 'sys_dict_type', ['code'], unique=True)
    op.create_table('sys_login_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_login_log_created_at'), 'sys_login_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_login_log_username'), 'sys_login_log', ['username'], unique=False)
    op.create_table('sys_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=True),
    sa.Column('component', sa.String(length=128), nullable=True),
    sa.Column('perm', sa.String(length=128), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_operation_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('request_body', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_operation_log_created_at'), 'sys_operation_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_path'), 'sys_operation_log', ['path'], unique=False)
    op.create_index(op.f('ix_sys_operation_log_user_id'), 'sys_operation_log', ['user_id'], unique=False)
    op.create_table('sys_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_role_code'), 'sys_role', ['code'], unique=True)
    op.create_table('sys_position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['sys_dept.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_role_menu',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['sys_menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'menu_id'),
    sa.UniqueConstraint('role_id', 'menu_id')
    )
    op.create_table('sys_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('is_super', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['sys_dept.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_table('msg_center',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_ids', sa.String(length=500), nullable=False),
    sa.Column('read_ids', sa.String(length=500), nullable=False),
    sa.Column('biz_type', sa.String(length=64), nullable=True),
    sa.Column('biz_id', sa.Integer(), nullable=True),
    sa.Column('push_miniapp', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_msg_center_created_at'), 'msg_center', ['created_at'], unique=False)
    op.create_index(op.f('ix_msg_center_type_code'), 'msg_center', ['type_code'], unique=False)
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    sa.UniqueConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_role')
    op.drop_index(op.f('ix_msg_center_type_code'), table_name='msg_center')
    op.drop_index(op.f('ix_msg_center_created_at'), table_name='msg_center')
    op.drop_table('msg_center')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_table('sys_role_menu')
    op.drop_table('sys_position')
    op.drop_index(op.f('ix_sys_role_code'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_operation_log_user_id'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_path'), table_name='sys_operation_log')
    op.drop_index(op.f('ix_sys_operation_log_created_at'), table_name='sys_operation_log')
    op.drop_table('sys_operation_log')
    op.drop_table('sys_menu')
    op.drop_index(op.f('ix_sys_login_log_username'), table_name='sys_login_log')
    op.drop_index(op.f('ix_sys_login_log_created_at'), table_name='sys_login_log')
    op.drop_table('sys_login_log')
    op.drop_index(op.f('ix_sys_dict_type_code'), table_name='sys_dict_type')
    op.drop_table('sys_dict_type')
    op.drop_index(op.f('ix_sys_dict_item_type_code'), table_name='sys_dict_item')
    op.drop_table('sys_dict_item')
    op.drop_table('sys_dept')
    # ### end Alembic commands ###
