"""add matching domain tables (pos_position, match_rule, match_result, match_push_log)

Revision ID: 513968600ebc
Revises: 40ffbb1d3136
Create Date: 2026-08-31 16:37:24.177633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513968600ebc'
down_revision: Union[str, None] = '40ffbb1d3136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('rule_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pos_position',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sys_position_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('filled', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['sys_dept.id'], ),
    sa.ForeignKeyConstraint(['sys_position_id'], ['sys_position.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_pos_position_name'), 'pos_position', ['name'], unique=False)
    op.create_table('match_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('talent_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('dimension_json', sa.Text(), nullable=True),
    sa.Column('explain', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['pos_position.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('talent_id', 'position_id')
    )
    op.create_index(op.f('ix_match_result_position_id'), 'match_result', ['position_id'], unique=False)
    op.create_index(op.f('ix_match_result_talent_id'), 'match_result', ['talent_id'], unique=False)
    op.create_table('match_push_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('target_user', sa.String(length=64), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match_result.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['msg_center.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_push_log_match_id'), 'match_push_log', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_push_log_match_id'), table_name='match_push_log')
    op.drop_table('match_push_log')
    op.drop_index(op.f('ix_match_result_talent_id'), table_name='match_result')
    op.drop_index(op.f('ix_match_result_position_id'), table_name='match_result')
    op.drop_table('match_result')
    op.drop_index(op.f('ix_pos_position_name'), table_name='pos_position')
    op.drop_table('pos_position')
    op.drop_table('match_rule')
    # ### end Alembic commands ###
